# Mateus Rodolfo 20220109
# Project Euler ID 2

"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""



even_sum = 0

current = [1, 2]

while current[-1] < 4000000:
    if current[-1] % 2 == 0:
            even_sum += current[-1]
    current[0], current [1] = current[1], current[0] + current[1]

print(even_sum)