#= Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. =#

evenSum = 0
currentPair = [1, 2]

while currentPair[2] < 4000000
    if currentPair[2] % 2 == 0
        global evenSum += currentPair[2]
    end
    currentPair[1], currentPair[2] = currentPair[2], currentPair[1] + currentPair[2]
end

println(evenSum)

# answer: 4613732